/* The bundled demo model.
 *
 * ENTIRELY SYNTHETIC. Every code sits in a deliberately high 9xxxxx range,
 * every description says "demo", and the model carries `synthetic: true`.
 * This is a dataset for trying the tool in ten seconds — `npx etim-json mcp
 * --demo` — not a fragment of the ETIM classification, and nothing in it may
 * be used as one. The real model is ETIM International's to distribute, under
 * ODC-BY, from etim-international.com.
 *
 * The shapes are the point: all four feature types, class-specific value
 * lists, metric/imperial unit pairs, a second language, a deprecated entry —
 * one of everything the format can carry, so the demo exercises the same
 * paths a real conversion does.
 */

import { FORMAT_VERSION, odcByAttribution, type EtimModel } from "./model.js";

export function demoModel(): EtimModel {
  return {
    formatVersion: FORMAT_VERSION,
    kind: "etim-model",
    release: "DEMO-1.0",
    languages: ["DE"],
    source: { type: "demo" },
    attribution: {
      ...odcByAttribution(),
      statement:
        "SYNTHETIC DEMO DATA generated by etim-json — not the ETIM classification model. " +
        "The real model is published by ETIM International under ODC-BY 1.0 at https://www.etim-international.com.",
    },
    synthetic: true,

    groups: {
      EG990001: {
        description: "Demo group — cables and accessories",
        translations: { DE: "Demogruppe — Kabel und Zubehör" },
      },
      EG990002: {
        description: "Demo group — switching and protection",
        translations: { DE: "Demogruppe — Schalt- und Schutzgeräte" },
      },
    },

    features: {
      EF990001: {
        type: "N",
        description: "Demo: outer diameter",
        translations: { DE: "Demo: Außendurchmesser" },
      },
      EF990002: {
        type: "A",
        description: "Demo: conductor material",
        translations: { DE: "Demo: Leitermaterial" },
      },
      EF990003: {
        type: "L",
        description: "Demo: halogen-free",
        translations: { DE: "Demo: halogenfrei" },
      },
      EF990004: {
        type: "R",
        description: "Demo: operating temperature",
        translations: { DE: "Demo: Betriebstemperatur" },
      },
      EF990005: {
        type: "N",
        description: "Demo: rated current",
        translations: { DE: "Demo: Bemessungsstrom" },
      },
      EF990006: {
        type: "A",
        description: "Demo: mounting method (deprecated in demo)",
        deprecated: true,
      },
    },

    values: {
      EV990001: { description: "Demo: copper", translations: { DE: "Demo: Kupfer" } },
      EV990002: { description: "Demo: aluminium", translations: { DE: "Demo: Aluminium" } },
      EV990003: { description: "Demo: tinned copper", translations: { DE: "Demo: verzinntes Kupfer" } },
      EV990004: { description: "Demo: DIN rail" },
      EV990005: { description: "Demo: surface mount" },
    },

    units: {
      EU990001: { description: "Demo: millimetre", abbreviation: "mm", translations: { DE: "Demo: Millimeter" } },
      EU990002: { description: "Demo: inch", abbreviation: "in" },
      EU990003: { description: "Demo: ampere", abbreviation: "A" },
      EU990004: { description: "Demo: degree Celsius", abbreviation: "°C" },
    },

    classes: {
      EC990001: {
        version: 3,
        description: "Demo: installation cable",
        groupCode: "EG990001",
        synonyms: ["demo mains cable", "demo building wire"],
        synonymTranslations: { DE: ["Demo-Installationsleitung"] },
        translations: { DE: "Demo: Installationskabel" },
        sectors: ["E"],
        features: [
          {
            code: "EF990001",
            orderNumber: 1,
            unitCode: "EU990001",
            unitImperialCode: "EU990002",
          },
          { code: "EF990002", orderNumber: 2, valueCodes: ["EV990001", "EV990002", "EV990003"] },
          { code: "EF990003", orderNumber: 3 },
          { code: "EF990004", orderNumber: 4, unitCode: "EU990004" },
        ],
      },
      EC990002: {
        version: 1,
        description: "Demo: miniature circuit breaker",
        groupCode: "EG990002",
        synonyms: ["demo MCB"],
        translations: { DE: "Demo: Leitungsschutzschalter" },
        sectors: ["E"],
        features: [
          { code: "EF990005", orderNumber: 1, unitCode: "EU990003" },
          { code: "EF990003", orderNumber: 2 },
          {
            code: "EF990006",
            orderNumber: 3,
            valueCodes: ["EV990004", "EV990005"],
            deprecated: true,
          },
        ],
      },
      EC990003: {
        version: 2,
        description: "Demo: cable gland",
        groupCode: "EG990001",
        translations: { DE: "Demo: Kabelverschraubung" },
        sectors: ["E"],
        features: [
          {
            code: "EF990001",
            orderNumber: 1,
            unitCode: "EU990001",
            unitImperialCode: "EU990002",
          },
          { code: "EF990003", orderNumber: 2 },
        ],
      },
    },
  };
}
