/* TypeScript declaration generation from a model.
 *
 * Emits literal union types for the codes present in a model plus a typed
 * class map, so downstream code can say `EtimClassCode` and get completion
 * and compile-time checking against the release actually in use.
 *
 * Unions are capped: TypeScript tooling degrades well before the ~5,500
 * class codes of a full release, and a 60,000-member value union helps
 * nobody. Over the cap, the type widens to `string` with the cap noted in
 * the emitted comment — visible, not silent.
 */

import type { EtimModel } from "./model.js";

export interface TypegenOptions {
  /** Above this many members a union widens to `string & {}`. */
  unionCap?: number;
  /** Identifier prefix, default "Etim". */
  prefix?: string;
}

const CAP_DEFAULT = 4000;

export function generateTypes(model: EtimModel, opts: TypegenOptions = {}): string {
  const cap = opts.unionCap ?? CAP_DEFAULT;
  /* NaN makes every `length > cap` false, emitting the very 60,000-member
     union the cap exists to prevent. */
  if (!Number.isSafeInteger(cap) || cap < 0) {
    throw new Error(`unionCap must be a non-negative whole number, got ${String(cap)}.`);
  }
  const p = opts.prefix ?? "Etim";
  /* The prefix is interpolated into every exported type name, so a caller
     passing "ETIM-" or "123" would silently emit a .d.ts that cannot parse.
     Fail at the call instead. */
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(p)) {
    throw new Error(
      `Type prefix ${JSON.stringify(p)} is not a valid TypeScript identifier — ` +
        "it becomes part of every exported type name (e.g. `${prefix}ClassCode`).",
    );
  }
  /* Everything model-controlled that lands inside a comment goes through
     this: a release label or attribution containing *​/ must not close the
     comment and inject declaration text. */
  const esc = (s: string) => s.replace(/\*\//g, "*\\/");

  const union = (name: string, codes: string[], doc: string): string => {
    const sorted = [...codes].sort();
    if (sorted.length === 0) {
      return `/** ${doc} — none present in this model. */\nexport type ${name} = never;\n`;
    }
    if (sorted.length > cap) {
      return (
        `/** ${doc} — ${sorted.length} codes, over the ${cap}-member union cap; ` +
        `widened to string. Regenerate with a higher cap to inline them. */\n` +
        `export type ${name} = string & {};\n`
      );
    }
    const members = sorted.map((c) => `  | "${c}"`).join("\n");
    return `/** ${doc} (${sorted.length}) */\nexport type ${name} =\n${members};\n`;
  };

  const classEntries = Object.entries(model.classes)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, c]) => {
      const desc = esc(c.description);
      return `  /** ${desc} (v${c.version}) */\n  "${code}": { description: string; version: ${c.version}; groupCode: ${p}GroupCode };`;
    })
    .join("\n");

  const head =
    `/* Generated by etim-json from release ${esc(model.release)}` +
    (model.synthetic ? " (SYNTHETIC DEMO DATA — not real ETIM classification)" : "") +
    `.\n * ${esc(model.attribution.statement)}\n * Do not edit by hand — regenerate from the model file. */\n\n`;

  return (
    head +
    union(`${p}ClassCode`, Object.keys(model.classes), "ETIM class codes in this model") +
    "\n" +
    union(`${p}GroupCode`, Object.keys(model.groups), "ETIM group codes in this model") +
    "\n" +
    union(`${p}FeatureCode`, Object.keys(model.features), "ETIM feature codes in this model") +
    "\n" +
    union(`${p}ValueCode`, Object.keys(model.values), "ETIM value codes in this model") +
    "\n" +
    union(`${p}UnitCode`, Object.keys(model.units), "ETIM unit codes in this model") +
    "\n" +
    `/** Class code → summary, for release ${esc(model.release)}. */\n` +
    `export interface ${p}ClassMap {\n${classEntries}\n}\n`
  );
}
